[package]
name = "yapf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "yapf"
path = "src/lib.rs"

[dependencies]
async-trait = "0.1.77"
http = "1.1.0"
hyper = "1.2.0"
rand = "0.8.4"
num-integer = "0.1.46"
rand_distr = "0.4.3"
anyhow = "1.0.40"
reqwest = { version = "0.11.3", features = ["default-tls", "trust-dns"] }
tokio = { version = "1.0.1", features = ["full"] }
arc-swap = "1.7.0"

[dev-dependencies]
wiremock = "0.6.0"
